In [2]:
## Q10: Produce a list of facilities with a total revenue less than 1000.
## The output of facility name and total revenue, sorted by revenue.
## Remember that there's a different cost for guests and members!

In [6]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """ SELECT guestquery.facility_name AS facility_name, (guestquery.guest_booking_revenue + memberquery.member_booking_revenue) AS revenue
FROM (
    SELECT f.name AS facility_name, SUM(f.guestcost * b.slots) AS guest_booking_revenue
    FROM Facilities AS f, Bookings AS b
    WHERE b.facid = f.facid
    AND b.memid=0
    GROUP BY facility_name
    ORDER BY guest_booking_revenue) guestquery
INNER JOIN (
SELECT f.name AS facility_name, SUM(f.membercost * b.slots) AS member_booking_revenue
    FROM Facilities AS f, Bookings AS b
    WHERE b.facid = f.facid 
    AND b.memid != 0
    GROUP BY facility_name
    ORDER BY member_booking_revenue) memberquery
ON guestquery.facility_name = memberquery.facility_name
WHERE (guestquery.guest_booking_revenue + memberquery.member_booking_revenue) < 3000
ORDER BY revenue DESC;"""
    
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 1906.5)
('Pool Table', 270)
('Snooker Table', 240)
('Table Tennis', 180)

In [ ]:
### Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order ###

In [10]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """ SELECT surname, firstname, memid, recommendedby
                 FROM Members
                 WHERE recommendedby LIKE '_%'
                 ORDER BY surname, firstname;"""
    
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader', 'Florence', 15, '9')
('Baker', 'Anne', 12, '9')
('Baker', 'Timothy', 16, '13')
('Boothe', 'Tim', 8, '3')
('Butters', 'Gerald', 5, '1')
('Coplin', 'Joan', 22, '16')
('Crumpet', 'Erica', 36, '2')
('Dare', 'Nancy', 7, '4')
('Genting', 'Matthew', 20, '5')
('Hunt', 'John', 35, '30')
('Jones', 'David', 11, '4')
('Jones', 'Douglas', 26, '11')
('Joplette', 'Janice', 4, '1')
('Mackenzie', 'Anna', 21, '1')
('Owen', 'Charles', 10, '1')
('Pinker', 'David', 17, '13')
('Purview', 'Millicent', 30, '2')
('Rumney', 'Henrietta', 27, '20')
('Sarwin', 'Ramnaresh', 24, '15')
('Smith', 'Jack', 14, '1')
('Stibbons', 'Ponder', 9, '6')
('Worthington-Smyth', 'Henry', 29, '2')

In [ ]:
### Q12: Find the facilities with their usage by member, but not guests ###

In [11]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """ SELECT f.name AS facility_name, SUM(b.slots) AS member_use
                 FROM Facilities as f, Bookings as b
                 WHERE f.facid = b.facid AND b.memid != 0
                 GROUP BY facility_name
                 ORDER by member_use DESC"""
    
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 1086)
('Tennis Court 1', 957)
('Massage Room 1', 884)
('Tennis Court 2', 882)
('Snooker Table', 860)
('Pool Table', 856)
('Table Tennis', 794)
('Squash Court', 418)
('Massage Room 2', 54)

In [ ]:
### Q13: Find the facilities usage by month, but not guests ###

In [12]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """ SELECT f.name AS facility_name, SUM(b.slots) AS member_use,
                 CASE WHEN b.starttime LIKE '2012-01%' THEN 'Jan'
                    WHEN b.starttime LIKE '2012-02%' THEN 'Feb'
                    WHEN b.starttime LIKE '2012-03%' THEN 'Mar'
                    WHEN b.starttime LIKE '2012-04%' THEN 'Apr'
                    WHEN b.starttime LIKE '2012-05%' THEN 'May'
                    WHEN b.starttime LIKE '2012-06%' THEN 'Jun'
                    WHEN b.starttime LIKE '2012-07%' THEN 'Jul'
                    WHEN b.starttime LIKE '2012-08%' THEN 'Aug'
                    WHEN b.starttime LIKE '2012-09%' THEN 'Sep'
                    WHEN b.starttime LIKE '2012-10%' THEN 'Oct'
                    WHEN b.starttime LIKE '2012-11%' THEN 'Nov'
                    ELSE 'Dec' END
                    AS month
            FROM Facilities as f, Bookings as b
            WHERE f.facid = b.facid AND b.memid != 0 AND b.starttime LIKE '2012-07%'
            GROUP BY facility_name
            ORDER BY facility_name;"""
    
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 165, 'Jul')
('Massage Room 1', 166, 'Jul')
('Massage Room 2', 8, 'Jul')
('Pool Table', 110, 'Jul')
('Snooker Table', 140, 'Jul')
('Squash Court', 50, 'Jul')
('Table Tennis', 98, 'Jul')
('Tennis Court 1', 201, 'Jul')
('Tennis Court 2', 123, 'Jul')